name: Build and Package

on:
  push:
    tags:
      - "*.*.*"

permissions:
  contents: write

defaults:
  run:
    shell: bash

env:
  RELEASE: ${{ github.run_number }}

jobs:
  build_windows_linux:
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 1
      GO111MODULE: on
      ZIG_VERSION: 0.11.0
      ZIG_SHA256: 2d00e789fec4f71790a6e7bf83ff91d564943c5ee843c5fd966efc474b423047

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: >-
          sudo apt-get update &&
          sudo apt-get install -y
          libgl-dev
          libx11-dev
          libxrandr-dev
          libxxf86vm-dev
          libxi-dev
          libxcursor-dev
          libxinerama-dev
          libxkbcommon-dev

      - name: Set up Go
        uses: WillAbides/setup-go-faster@v1.14.0
        with:
          go-version-file: 'go.mod'

      - name: Set up Zig
        run: |
          PATH=/usr/local/zig:${PATH}
          echo "PATH=${PATH}" >> $GITHUB_ENV

          set -eux
          url="https://ziglang.org/download/${ZIG_VERSION}/zig-linux-x86_64-${ZIG_VERSION}.tar.xz"
          sha256="${ZIG_SHA256}"

          curl -sSL ${url} -o zig.tar.xz
          echo ${sha256} zig.tar.xz | sha256sum -c -
          sudo tar -C /usr/local -Jxvf zig.tar.xz
          sudo mv /usr/local/zig-* /usr/local/zig
          rm zig.tar.xz
          zig version

      - name: Build for Linux (amd64)
        run: >-
          env GOARCH=amd64 go build -trimpath -ldflags="-s -w" -o bin/linux/sharify-desktop-amd64 .

      - name: Build for Windows (amd64)
        run: >-
          env
          GOARCH=amd64
          GOOS=windows
          CC="zig cc -target x86_64-windows-gnu -Wl,--subsystem,windows -Wl,-s"
          CXX="zig c++ -target x86_64-windows-gnu -Wl,--subsystem,windows -Wl,-s"
          go build -trimpath
          -ldflags="-H=windowsgui"
          -o bin/windows/sharify-desktop-amd64.exe
          .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-linux-binaries
          path: bin
          retention-days: 1

  build_macos:
    runs-on: macos-latest
    env:
      CGO_ENABLED: 1
      GO111MODULE: on

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: WillAbides/setup-go-faster@v1.14.0
        with:
          go-version-file: 'go.mod'

      - name: Build for amd64
        run: >-
          env
          GOARCH=amd64
          GOOS=darwin
          go build -trimpath -buildmode=pie
          -ldflags="-s -w"
          -o bin/darwin/sharify-desktop-amd64
          .

      - name: Build for arm64
        run: >-
          env
          GOARCH=arm64
          GOOS=darwin
          go build -trimpath -buildmode=pie
          -ldflags="-s -w"
          -o bin/darwin/sharify-desktop-arm64
          .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-binaries
          path: bin/darwin
          retention-days: 1

  package_windows:
    runs-on: windows-latest
    needs: build_windows_linux
    steps:
      - name: Checkout .iss files
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            pkg/windows

      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          name: windows-linux-binaries
          path: bin

      - name: Prepare for packaging
        run: |
          # Set variables for .iss file paths
          AMD_ISS=pkg/windows/iss/SharifyDesktop-amd64.iss

          # Edit versions in iss files
          sed -i "s/#define MyAppVersion \"1.0.0\"/#define MyAppVersion \"${{ github.ref_name }}\"/" "$AMD_ISS"

          # Export env variables
          echo "AMD_ISS=${AMD_ISS}" >> $GITHUB_ENV

      - name: Package with Inno Setup
        run: |
          iscc.exe "$AMD_ISS"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-installers
          path: build/out
          retention-days: 1

  package_linux:
    runs-on: [ ubuntu-latest ]
    needs: build_windows_linux
    steps:
      - name: Checkout pkg files
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            pkg/linux

      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          name: windows-linux-binaries
          path: bin

      - name: Install dependencies
        run: >-
          sudo apt-get update &&
          sudo apt-get install -y
          rpm
          debhelper
          devscripts
          dpkg-dev

      - name: Prepare for packaging
        run: |
          # Edit version in specs/control files
          sed -i "s/^Version:.*/Version: ${{ github.ref_name }}/" pkg/linux/rpm/SPECS/sharify.spec
          sed -i "s/^Release:.*/Release: ${RELEASE}/" pkg/linux/rpm/SPECS/sharify.spec

          # Set up rpmbuild/debbuild file tree
          mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}

          # Copy resources
          cp -r pkg/linux/rpm/* ~/rpmbuild/
          # Copy binaries
          cp bin/linux/sharify-desktop-amd64 ~/rpmbuild/SOURCES/
          
          # Make binaries executable
          chmod +x ~/rpmbuild/SOURCES/sharify-desktop-amd64

          # Create output folder
          mkdir -p build/out

      - name: Package .rpm (amd64)
        run: >-
          rpmbuild -bb
          ~/rpmbuild/SPECS/sharify.spec
          --define "_rpmdir build/out"
          --target=x86_64

      - name: Tidy artifact
        run: |
          cp -r build/out/x86_64/* build/out/
          rm -rf build/out/x86_64

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-installers
          path: build/out
          retention-days: 1

  package_macos:
    runs-on: macos-latest
    needs: build_macos
    steps:
      - name: Checkout pkg/darwin
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            pkg/darwin

      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          name: macos-binaries
          path: bin

      - name: Set up environment
        run: |
          # Set env variables for paths
          APP="pkg/darwin/Sharify Desktop.app/Contents"

          # Create necessary folders
          mkdir "${APP}/MacOS"
          mkdir -p build/out/

          # Replace version in Info.plist files
          sed -i '' "s/<string>1.0.0<\/string>/<string>${{ github.ref_name }}<\/string>/" "${APP}/Info.plist"

          # Move compiled binary
          cp bin/sharify-desktop-amd64 "${APP}/MacOS/sharify-desktop-amd64"

          # Set permissions
          chmod +x "${APP}/MacOS/sharify-desktop-amd64"

          # Export APP env for later
          echo "APP=${APP}" >> $GITHUB_ENV

      - name: Package for amd64
        run: >-
          pkgbuild
          --root pkg/darwin
          --identifier pro.sharify.desktop
          --version "${{ github.ref_name }}"
          --install-location /Applications
          "build/out/SharifyDesktopSetup-${{ github.ref_name }}-x86_64.pkg"

      - name: Swap and64 binary for arm64
        run: |
          rm -f "${APP}/MacOS/sharify-desktop-amd64"
          cp bin/sharify-desktop-arm64 "${APP}/MacOS/sharify-desktop-arm64"
          sed -i '' 's/amd64/arm64/g' "${APP}/Info.plist"
          chmod +x "${APP}/MacOS/sharify-desktop-arm64"

      - name: Package for arm64
        run: >-
          pkgbuild
          --root pkg/darwin
          --identifier pro.sharify.desktop
          --version "${{ github.ref_name }}"
          --install-location /Applications
          "build/out/SharifyDesktopSetup-${{ github.ref_name }}-ARM64.pkg"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-installers
          path: build/out
          retention-days: 1

  release:
    needs: [ package_windows, package_linux, package_macos ]
    runs-on: ubuntu-latest
    steps:
      - name: Download
        uses: actions/download-artifact@v4
        with:
          path: all

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: v${{ github.ref_name }}
          files: |
            all/windows-installers/*
            all/linux-installers/*
            all/macos-installers/*
          make_latest: true
          fail_on_unmatched_files: true
